import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import TopBar from '@/widgets/top-bar/TopBar'
import Header from '@/widgets/header/Header'
import './globals.scss'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <TopBar />
        <Header />
        <div className="wrapper_content">{children}</div>
      </body>
    </html>
  )
}
